In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df =sns.load_dataset("tips")

In [3]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [4]:
#predict whats the time if lunch or dinner >> target is time
#encoding, missing value treatment, scaling>> aoutomate

In [4]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [5]:
df['time'] = label.fit_transform(df['time'])

In [6]:
df['time'].unique()

array([0, 1])

In [7]:
x = df.drop('time',axis=1)

In [8]:
y = df['time']

In [9]:
from sklearn.linear_model import LinearRegression

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [13]:
x_train

     total_bill   tip     sex smoker   day  size
0         16.99  1.01  Female     No   Sun     2
154       19.77  2.00    Male     No   Sun     4
167       31.71  4.50    Male     No   Sun     4
110       14.00  3.00    Male     No   Sat     2
225       16.27  2.50  Female    Yes   Fri     2
..          ...   ...     ...    ...   ...   ...
137       14.15  2.00  Female     No  Thur     2
72        26.86  3.14  Female    Yes   Sat     2
140       17.47  3.50  Female     No  Thur     2
235       10.07  1.25    Male     No   Sat     2
37        16.93  3.07  Female     No   Sat     3

[195 rows x 6 columns]

In [11]:
#handling categorical data > data encoding >> feature scaling
from sklearn.impute import SimpleImputer #for missing value
from sklearn.preprocessing import OneHotEncoder #for encoding the data
from sklearn.preprocessing import StandardScaler # fro scaling

from sklearn.pipeline import Pipeline # a sequence of data transformer
from sklearn.compose import ColumnTransformer ##to group all the steps for specific columns

In [12]:
cat_cols = ["sex","smoker","day"]
num_cols = ["total_bill","tip","size"]

In [13]:
#feture engineering automation using pipeline and colomntransfer

num_pip =Pipeline(steps=[('imputation',SimpleImputer(strategy="median")),
                          ('scalin',StandardScaler())])
cat_pip =Pipeline(steps=[('imputation',SimpleImputer(strategy="most_frequent")),
                          ('encoding', OneHotEncoder())])

In [14]:
preprocsscor =ColumnTransformer([("num_pipline",num_pip, num_cols),
                   ("categ_pipeline",cat_pip,cat_cols)])

In [15]:
x_train =preprocsscor.fit_transform(x_train)
x_test =preprocsscor.transform(x_test)

In [45]:
pd.DataFrame(x_test)

          0         1         2    3    4    5    6    7    8    9    10
0  -1.853764 -1.482098 -1.601718  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0
1  -0.084533  0.049847 -0.577669  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0
2   0.795015  0.363896  0.446380  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0
3  -0.593567 -0.333139 -0.577669  0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0
4   0.183498  0.049847 -0.577669  0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0
5  -1.327837 -1.145070 -0.577669  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0
6  -0.933674 -0.899959 -0.577669  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0
7   0.154218  0.432833  0.446380  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0
8  -0.568791 -0.716125 -0.577669  0.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0
9   0.569778  0.517090  1.470429  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0
10 -0.830065 -0.562931 -0.577669  0.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0
11 -1.063185 -0.716125 -0.577669  1.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0
12  1.171159  1.635410  1.470429  0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0
13  0.639602  1.037952 -0.577669  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0
14  3.522626  5.411654  0.446380  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0
15  0.353552 -0.716125 -0.577669  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0
16  0.427880  2.079674 -0.577669  0.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0
17 -1.040661 -0.256542 -0.577669  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0
18 -0.770377 -0.716125 -0.577669  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0
19  0.861459 -0.716125 -0.577669  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0
20  1.194809  0.118785  1.470429  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0
21 -0.197151  0.256660 -0.577669  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0
22 -0.361574  1.045611 -0.577669  1.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0
23  0.409861  2.730751  1.470429  0.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0
24 -0.799658 -0.869320 -0.577669  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0
25 -1.000118 -1.099112 -0.577669  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0
26  0.108044  0.861778 -0.577669  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0
27  0.647485  1.581792 -0.577669  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0
28 -0.094669 -0.478674  0.446380  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0
29  1.185800 -0.716125  0.446380  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0
30 -0.735466 -0.716125 -0.577669  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0
31  1.224090  2.041375  1.470429  0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0
32 -0.958450 -0.731445 -0.577669  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0
33  1.835606  1.329021  0.446380  1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0
34  1.722988  1.712007  1.470429  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0
35 -0.688166 -1.037834 -0.577669  0.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0
36  1.322068  1.581792  0.446380  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0
37 -0.132959 -0.333139  1.470429  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0
38 -0.288372  0.432833  0.446380  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0
39 -0.941557 -1.099112 -0.577669  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0
40  0.512343 -0.011431  1.470429  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0
41  0.126063  0.317937  0.446380  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0
42  0.333280  0.432833 -0.577669  0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0
43 -0.509103 -0.647188 -0.577669  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0
44  0.130568 -0.371438  1.470429  1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0
45  1.063046  0.049847 -0.577669  0.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0
46  0.510091  0.509431  0.446380  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0
47  1.771414  1.581792  1.470429  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0
48  0.013445  0.049847 -0.577669  1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0

In [24]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

In [28]:
models = {"support vectot classifier":SVC(),
         "dt classifire": DecisionTreeClassifier(),
         "random_forest": RandomForestClassifier()}

In [29]:
from sklearn.metrics import accuracy_score
def model_train_eval(x_train,y_train,x_test,y_test,models):
    evaluation = {}
    for i in range(len(models)):
        model = list(models.values())[i]
        model.fit(x_train,y_train)
        y_pred = model.predict(x_test)
        model_score = accuracy_score(y_test,y_pred)
        evaluation[list(models.keys())[i]] = model_score
    return evaluation

In [30]:
model_train_eval(x_train, y_train,x_test,y_test,models)

{'support vectot classifier': 0.9183673469387755,
 'dt classifire': 0.9183673469387755,
 'random_forest': 0.8979591836734694}

In [16]:
from sklearn.ensemble import RandomForestClassifier

In [17]:
forest =RandomForestClassifier()

In [18]:
from sklearn.model_selection import RandomizedSearchCV
params ={'max_depth':[1,2,3,5,10,None],
         'n_estimators':[50,100,200,300],
         'criterion':['gini','entropy']}

In [19]:
cv = RandomizedSearchCV(forest, param_distributions=params, cv=5,verbose=3,scoring='accuracy')

In [21]:
cv.fit(x_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV 1/5] END criterion=entropy, max_depth=None, n_estimators=200;, score=0.923 total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=None, n_estimators=200;, score=0.949 total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=None, n_estimators=200;, score=1.000 total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=None, n_estimators=200;, score=0.974 total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=None, n_estimators=200;, score=0.974 total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=3, n_estimators=200;, score=0.923 total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=3, n_estimators=200;, score=0.974 total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=3, n_estimators=200;, score=1.000 total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=3, n_estimators=200;, score=1.000 total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=3, n_estimators=200;, score=1.000 total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=2, n_estimators=200;, score=0.923 total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=2, n_estimators=200;, score=0.974 total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=2, n_estimators=200;, score=1.000 total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=2, n_estimators=200;, score=1.000 total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=2, n_estimators=200;, score=1.000 total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=3, n_estimators=50;, score=0.923 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=3, n_estimators=50;, score=0.974 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=3, n_estimators=50;, score=0.974 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=3, n_estimators=50;, score=1.000 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=3, n_estimators=50;, score=1.000 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=None, n_estimators=300;, score=0.923 total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=None, n_estimators=300;, score=0.974 total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=None, n_estimators=300;, score=1.000 total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=None, n_estimators=300;, score=0.974 total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=None, n_estimators=300;, score=0.974 total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=2, n_estimators=200;, score=0.923 total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=2, n_estimators=200;, score=0.974 total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=2, n_estimators=200;, score=1.000 total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=2, n_estimators=200;, score=1.000 total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=2, n_estimators=200;, score=1.000 total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=1, n_estimators=50;, score=0.923 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=1, n_estimators=50;, score=0.974 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=1, n_estimators=50;, score=1.000 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=1, n_estimators=50;, score=1.000 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=1, n_estimators=50;, score=0.692 total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=10, n_estimators=100;, score=0.923 total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=10, n_estimators=100;, score=0.974 total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=10, n_estimators=100;, score=1.000 total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=10, n_estimators=100;, score=0.974 total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=10, n_estimators=100;, score=0.974 total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=1, n_estimators=100;, score=0.795 total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=1, n_estimators=100;, score=0.949 total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=1, n_estimators=100;, score=0.821 total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=1, n_estimators=100;, score=0.949 total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=1, n_estimators=100;, score=0.897 total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=1, n_estimators=300;, score=0.923 total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=1, n_estimators=300;, score=0.974 total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=1, n_estimators=300;, score=0.949 total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=1, n_estimators=300;, score=0.949 total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=1, n_estimators=300;, score=1.000 total time=   0.5s

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(),
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [1, 2, 3, 5, 10, None],
                                        'n_estimators': [50, 100, 200, 300]},
                   scoring='accuracy', verbose=3)

In [22]:
cv.best_params_

{'n_estimators': 200, 'max_depth': 3, 'criterion': 'entropy'}

In [23]:
cv.best_score_

np.float64(0.9794871794871796)

In [31]:
from sklearn.datasets import make_classification
x,y = make_classification(n_samples=1000,n_features=20,n_classes=2,random_state=1)
rf_cls = RandomForestClassifier(n_estimators=100,oob_score=True,random_state=1)
rf_cls.fit(x,y)
oob_score = rf_cls.oob_score_
print("out-of-bag score", oob_score)

out-of-bag score 0.861