In [23]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\taherali\anaconda3\lib\site-packages (9.5.0)

In [24]:
import mysql.connector as conn

In [25]:
mydb=conn.connect(host='localhost',user='root',passwd="Tah786110$")

In [26]:
mydb

In [27]:
cursor = mydb.cursor()

In [28]:
cursor.execute("show databases")

In [29]:
cursor.fetchall()

[('information_schema',),
 ('mysql',),
 ('performance_schema',),
 ('pwskillsmysql',),
 ('pysqldb',),
 ('sys',),
 ('taher',)]

In [30]:
cursor.execute("create database pysqldb")

DatabaseError: 1007 (HY000): Can't create database 'pysqldb'; database exists

In [ ]:
cursor.execute("create table pysqldb.pwskills(studentid INT(10),firstname VARCHAR(30), lastname VARCHAR(30),regid INT(30), classname VARCHAR(30))")

In [ ]:
cursor.execute('use pysqldb')

In [ ]:
cursor.execute("show tables")

In [ ]:
cursor.fetchall()

[('pwskills',)]

In [ ]:
cursor.execute("insert into pysqldb.pwskills values(45,'Taher','sahil',34,'fsds')")

In [ ]:
mydb.commit()

In [ ]:
cursor.execute('select * from pysqldb.pwskills')

In [ ]:
cursor.fetchall()

[(45, 'Taher', 'sahil', 34, 'fsds')]

In [ ]:
ls

 Volume in drive C is Windows
 Volume Serial Number is 9262-288D

 Directory of c:\Users\TAHERALI\Downloads

12-01-2026  21:17    <DIR>          .
10-01-2026  21:03    <DIR>          ..
28-11-2025  08:04       958,742,216 Anaconda3-2025.06-0-Windows-x86_64.exe
08-01-2026  22:00            65,854 Bokeh.ipynb
28-12-2025  13:15            10,815 class and static method.ipynb
28-12-2025  14:40             8,463 decorators (1).ipynb
20-12-2025  22:09            31,921 dictionary.ipynb
22-12-2025  22:48                 0 file.txt
13-12-2025  00:50            33,574 functions.ipynb
12-01-2026  20:21             2,052 learn mysql2.sql
13-12-2025  19:41            56,689 List.ipynb
28-11-2025  04:45         1,106,976 Microsoft 365 Copilot Installer (1).exe
10-01-2026  22:04       585,392,128 mysql-installer-community-8.0.44.0.msi
03-01-2026  21:38           228,170 pandas_advance_1.ipynb
07-01-2026  20:04           224,310 pandas_advance-2 (1).ipynb
03-01-2026  23:17           223,659 pandas_advance-2.ipynb
07-01-2026  21:04           784,138 plotly.ipynb
20-12-2025  22:09            21,588 polymorphism and encapsulation.ipynb
25-12-2025  20:46             2,537 property decorator.ipynb
24-12-2025  23:37             2,569 pwskills-20240320T071201Z-001.zip
29-11-2025  04:23            10,111 Python_Objects,_Number_&_Booleans,_Strings.ipynb
08-01-2026  21:18         1,874,355 seabon file.ipynb
07-01-2026  21:05         1,922,912 seaborn.ipynb
02-01-2026  17:35            19,128 services.csv
12-01-2026  21:17            81,383 sqlcode.ipynb
20-12-2025  22:09            40,067 Strings.ipynb
10-01-2026  15:58            43,485 students.csv
10-01-2026  15:59         2,288,450 superstore.csv
23-12-2025  21:47             3,934 visual studio python.ipynb
12-01-2026  21:17             2,566 vs to sql.ipynb
20-12-2025  22:00       124,369,816 VSCodeUserSetup-x64-1.107.1.exe
12-01-2026  20:58           179,120 Zoom_cm_ds_mbAGQo3iUImUK8sNZYl5TnIpx+mEkQDjG9uSi@JoRMWjuc0ecLCDyp_kb572efab51b29046_.exe
              30 File(s)  1,677,772,986 bytes
               2 Dir(s)  405,164,249,088 bytes free

In [ ]:
cursor.execute('create table pysqldb.glassdata(col1 INT(10) ,col2 float(10,5),col3 float(10,5) ,col4 float(10,5) , col5 float(10,5),col6 float(10,5) ,clo7 float(10,5) , col8 float(10,5) , col9 float(10,5) , col10 float(10,5) , col11 INT(10)) ')

In [ ]:
cursor.execute('insert into pysqldb.glassdata values(1,1.52101,13.64,4.49,1.10,71.78,0.06,8.75,0.00,0.00,1)')

In [ ]:
mydb.commit()

In [33]:
import csv
with open('glass.data','r') as f:
    glass_data=csv.reader(f,delimiter=',')
    for i in glass_data:
        print(type(i[0]))
        print(f'insert into glassdata values ({str(i[0])})')
        cursor.execute('insert into pysqldb.glassdata values({values})'.format(values = ((i[0]))))

<class 'str'>
insert into glassdata values (1)

DataError: 1136 (21S01): Column count doesn't match value count at row 1

In [34]:
glass_data

In [ ]:
import pandas as pd

In [ ]:
pd.read_sql('select * from pysqldb.pwskills',mydb)

C:\Users\TAHERALI\AppData\Local\Temp\ipykernel_23044\3652025134.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql('select * from pysqldb.pwskills',mydb)

   studentid firstname lastname  regid classname
0         45     Taher    sahil     34      fsds

In [ ]:
pd.read_sql('show databases', mydb)

C:\Users\TAHERALI\AppData\Local\Temp\ipykernel_23044\3468230276.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql('show databases', mydb)

             Database
0  information_schema
1               mysql
2  performance_schema
3       pwskillsmysql
4             pysqldb
5                 sys
6               taher

In [35]:
pip install "pymongo[srv]==3.12"

Requirement already satisfied: pymongo==3.12 in c:\users\taherali\anaconda3\lib\site-packages (from pymongo[srv]==3.12) (3.12.0)
Requirement already satisfied: dnspython<2.0.0,>=1.16.0 in c:\users\taherali\anaconda3\lib\site-packages (from pymongo[srv]==3.12) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [36]:
import pymongo

In [37]:
client = pymongo.MongoClient("mongodb+srv://taherali535251_db_user:Tah786110@cluster0.eobina9.mongodb.net/?appName=Cluster0")

In [38]:
client

MongoClient(host=['ac-dyhukzt-shard-00-02.eobina9.mongodb.net:27017', 'ac-dyhukzt-shard-00-01.eobina9.mongodb.net:27017', 'ac-dyhukzt-shard-00-00.eobina9.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, appname='Cluster0', authsource='admin', replicaset='atlas-8j37j5-shard-0', ssl=True)

In [39]:
db = client["pwskills"]

In [40]:
coll_create = db["my_record"]

In [41]:
data = {"name":"Taher",
        "class":"Dataanalyst stud",
        "timing":"flexi"
        }

In [42]:
coll_create.insert_one(data)

In [43]:
data2 = {"list_course":["data analytisc","java","python",],
         "mentor":["Rajiv","Imran","Ajay"]}

In [44]:
coll_create.insert_one(data2)

In [45]:
for i in coll_create.find():
    print(i)

{'_id': ObjectId('69665d0e3ed2332a724e8b61'), 'name': 'Taher', 'class': 'Dataanalyst stud', 'timing': 'flexi'}
{'_id': ObjectId('69665fb73ed2332a724e8b63'), 'name': 'Taher', 'class': 'Dataanalyst stud', 'timing': 'flexi'}
{'_id': ObjectId('6966602d3ed2332a724e8b64'), 'list_course': ['data analytisc', 'java', 'python'], 'mentor': ['Rajiv', 'Imran', 'Ajay']}

In [46]:
data3 = [
  { "name": "Amy", "address": "Apple st 652" },
  { "name": "Hannah", "address": "Mountain 21" },
  { "name": "Michael", "address": "Valley 345" },
  { "name": "Sandy", "address": "Ocean blvd 2" },
  { "name": "Betty", "address": "Green Grass 1" },
  { "name": "Richard", "address": "Sky st 331" },
  { "name": "Susan", "address": "One way 98" },
  { "name": "Vicky", "address": "Yellow Garden 2" },
  { "name": "Ben", "address": "Park Lane 38" },
  { "name": "William", "address": "Central st 954" },
  { "name": "Chuck", "address": "Main Road 989" },
  { "name": "Viola", "address": "Sideway 1633" }
]

In [47]:
coll_create.insert_many(data3)

In [58]:
data4 =list_of_records = [
    {'companyName': 'pw skills',
     'product': 'Affordable AI',
     'courseOffered': 'Machine Learning with Deployment'},
    
    {'companyName': 'pw skills',
     'product': 'Affordable AI',
     'courseOffered': 'Deep Learning for NLP and Computer vision'},
    
    {'companyName': 'pw skills',
     'product': 'Master Program',
     'courseOffered': 'Data Science Masters Program'}
]

In [59]:
coll_create.insert_many(data4)

In [60]:
for i in coll_create.find():
    print(i)

{'_id': ObjectId('69665d0e3ed2332a724e8b61'), 'name': 'Taher', 'class': 'Dataanalyst stud', 'timing': 'flexi'}
{'_id': ObjectId('69665fb73ed2332a724e8b63'), 'name': 'Taher', 'class': 'Dataanalyst stud', 'timing': 'flexi'}
{'_id': ObjectId('6966602d3ed2332a724e8b64'), 'list_course': ['data analytisc', 'java', 'python'], 'mentor': ['Rajiv', 'Imran', 'Ajay']}
{'_id': ObjectId('6966624e3ed2332a724e8b65'), 'name': 'Amy', 'address': 'Apple st 652'}
{'_id': ObjectId('6966624e3ed2332a724e8b66'), 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': ObjectId('6966624e3ed2332a724e8b67'), 'name': 'Michael', 'address': 'Valley 345'}
{'_id': ObjectId('6966624e3ed2332a724e8b68'), 'name': 'Sandy', 'address': 'Ocean blvd 2'}
{'_id': ObjectId('6966624e3ed2332a724e8b69'), 'name': 'Betty', 'address': 'Green Grass 1'}
{'_id': ObjectId('6966624e3ed2332a724e8b6a'), 'name': 'Richard', 'address': 'Sky st 331'}
{'_id': ObjectId('6966624e3ed2332a724e8b6b'), 'name': 'Susan', 'address': 'One way 98'}
{'_id': ObjectId('6966624e3ed2332a724e8b6c'), 'name': 'Vicky', 'address': 'Yellow Garden 2'}
{'_id': ObjectId('6966624e3ed2332a724e8b6d'), 'name': 'Ben', 'address': 'Park Lane 38'}
{'_id': ObjectId('6966624e3ed2332a724e8b6e'), 'name': 'William', 'address': 'Central st 954'}
{'_id': ObjectId('6966624e3ed2332a724e8b6f'), 'name': 'Chuck', 'address': 'Main Road 989'}
{'_id': ObjectId('6966624e3ed2332a724e8b70'), 'name': 'Viola', 'address': 'Sideway 1633'}
{'_id': ObjectId('6966651a3ed2332a724e8b71'), 'companyName': 'pw skills', 'product': 'Affordable AI', 'courseOffered': 'Machine Learning with Deployment'}
{'_id': ObjectId('6966651a3ed2332a724e8b72'), 'companyName': 'pw skills', 'product': 'Affordable AI', 'courseOffered': 'Deep Learning for NLP and Computer vision'}
{'_id': ObjectId('6966651a3ed2332a724e8b73'), 'companyName': 'pw skills', 'product': 'Master Program', 'courseOffered': 'Data Science Masters Program'}

In [61]:
data5 = [
    {'_id': '3', 'companyName': 'pw skills', 'Faculty': 'XYZ'},
    {'_id': '4', 'companyName': 'pw skills', 'Faculty': 'ABC'},
    {'_id': '5', 'companyName': 'pw skills', 'Faculty': 'PQR'},
]

In [62]:
coll_create.insert_many(data5)

In [63]:
coll_create.find_one()

{'_id': ObjectId('69665d0e3ed2332a724e8b61'),
 'name': 'Taher',
 'class': 'Dataanalyst stud',
 'timing': 'flexi'}

In [65]:
for i in coll_create.find({'companyName':'pw skills'}):
    print(i)

{'_id': ObjectId('6966651a3ed2332a724e8b71'), 'companyName': 'pw skills', 'product': 'Affordable AI', 'courseOffered': 'Machine Learning with Deployment'}
{'_id': ObjectId('6966651a3ed2332a724e8b72'), 'companyName': 'pw skills', 'product': 'Affordable AI', 'courseOffered': 'Deep Learning for NLP and Computer vision'}
{'_id': ObjectId('6966651a3ed2332a724e8b73'), 'companyName': 'pw skills', 'product': 'Master Program', 'courseOffered': 'Data Science Masters Program'}
{'_id': '3', 'companyName': 'pw skills', 'Faculty': 'XYZ'}
{'_id': '4', 'companyName': 'pw skills', 'Faculty': 'ABC'}
{'_id': '5', 'companyName': 'pw skills', 'Faculty': 'PQR'}

In [68]:
for i in coll_create.find({'_id':{'$gte':'4'}}):
    print(i)

{'_id': '4', 'companyName': 'pw skills', 'Faculty': 'ABC'}
{'_id': '5', 'companyName': 'pw skills', 'Faculty': 'PQR'}

In [ ]:
coll_create.update_many({'companyName':"pw skills"},{"$set":{'companyName':"pw"}})